"""Second migration

Revision ID: 0ce148f5e1fa
Revises: 556e6fc999ab
Create Date: 2020-05-13 14:49:07.188865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce148f5e1fa'
down_revision = '556e6fc999ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('available_money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('tickets_bought', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['accounts.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('event', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('event', 'date',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('event', 'place',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('event', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event', 'total_available_tickets',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'total_available_tickets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'place',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('event', 'date',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('event', 'city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_table('orders')
    op.drop_table('accounts')
    # ### end Alembic commands ###
